### ISSUE TITLE
Training problems about the ScanObjectNN

### ISSUE THREAD

**Issue by psp3dcg** [FabianFuchsML/se3-transformer-public#29]
Hi! Awesome work! Have the challenges of SE(3)-Transformer code on ScanObjectNN been solved?

**Comment by FabianFuchsML** [comment]
Thank you! :) We decided to not re-implement the ScanObjectNN code. However, since Nvidia published the accelerated version, I would recommend anyone to use their version of the code anyway (you would have to write a dataloader for ScanObjectNN yourself though). They managed to speed up training of the SE(3)-Transformer by up to 21 times and reduced memory consumption by up to 43 times, which is obviously amazing.

https://developer.nvidia.com/blog/accelerating-se3-transformers-training-using-an-nvidia-open-source-model-implementation/

**Comment by psp3dcg** [comment]
> Thank you! :) We decided to not re-implement the ScanObjectNN code. However, since Nvidia published the accelerated version, I would recommend anyone to use their version of the code anyway (you would have to write a dataloader for ScanObjectNN yourself though). They managed to speed up training of the SE(3)-Transformer by up to 21 times and reduced memory consumption by up to 43 times, which is obviously amazing.
> 
> https://developer.nvidia.com/blog/accelerating-se3-transformers-training-using-an-nvidia-open-source-model-implementation/

OK, thank you~ I will see the se3-network of nvidia version
